name: mdmottu
description: Aplicativo de teste - Mottu.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dartz: ^0.10.1
  equatable: ^2.0.3
  dio: ^4.0.6
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  connectivity_plus: ^2.3.6+1
  get_it: ^7.2.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - "assets/images/"